---
apiVersion: v1
kind: Secret
metadata:
  name: cookie-secret
type: Opaque
data:
  secret: c2VjcmV0cGFzc3dvcmQ=  # This is the base64 encoded value of "secretpassword"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizmaker
  template:
    metadata:
      labels:
        app: quizmaker
    spec:
      containers:
        - name: quizmaker
          image: quay.io/jimmykarily/quizmaker:latest
          command: ["/bin/quizmaker"]
          args:
            - "-question-pool"
            - "/data/questions.yaml"
          env:
            - name: GIN_MODE
              value: release
            - name: QUIZMAKER_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: cookie-secret
                  key: secret
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /quizmaker-data
            type: Directory 

---
apiVersion: v1
kind: Service
metadata:
  name: quizmaker
spec:
  type: NodePort
  selector:
    app: quizmaker
  ports:
  - protocol: TCP
    port: 80          # Port that the service will expose inside the cluster
    targetPort: 8080  # Port on the container that the service will forward traffic to
    nodePort: 30000   # Port on each node that will forward traffic to the service
