apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizmaker
  template:
    metadata:
      labels:
        app: quizmaker
    spec:
      containers:
        - name: quizmaker
          image: quay.io/jimmykarily/quizmaker:v0.0.10
          ports:
            - containerPort: 8080
          command: ["quizmaker", "-question-pool", "/app/questions.yaml", "-database-storage-dir", "/data/quizmaker"]
          volumeMounts:
            - name: questions
              mountPath: /app/questions.yaml
              subPath: questions.yaml
            - name: host-data
              mountPath: /data/quizmaker
          env:
            - name: GIN_MODE
              value: release
            - name: QUIZMAKER_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: quizmaker-secret
                  key: token
            - name: VERIFICATION_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: quizmaker-secret
                  key: verificationEndpoint
      volumes:
        - name: questions
          configMap:
            name: quizmaker-questions
        - name: host-data
          hostPath:
            path: /home/kairos/
            type: Directory
